BottomNavigationBarのアイコンを実装
taowata/connpass-app-intern pull request #34
Opened 2020-08-29 19:01 UTC by syuheifujita

issue
#22 

やったこと
・アイコンを実装
・アイコンがタップされているときに，消えてしまうバグを修正

参考
http://hamup.hatenablog.com/entry/2019/06/09/194906

2020-08-30 03:16 UTC, syuheifujita commented
@taowata 
お手隙の際に，レビューお願いします！

2020-08-30 03:23 UTC, taowata commented
@syuheifujita 
了解です!
時間あるとき確認します〜

2020-08-30 03:43 UTC, syuheifujita commented
> @syuheifujita
> 了解です!
> 時間あるとき確認します〜

🙏

2020-08-31 04:13 UTC, taowata reviewed
現状だとユーザーがどのナビゲーションボタンを押しているかが分かりにくいから、非選択ボタンはグレーに選択ボタンはホワイトにするような仕様にした方が良い。
selectorで検索してみると色々情報出てくるよ！

2020-09-06 16:57 UTC, syuheifujita commented
![Screenshot_1599411440](https://user-images.githubusercontent.com/38001967/92330899-80d9fe80-f0ad-11ea-97c9-c9a544ce2692.png)

2020-09-06 17:00 UTC, syuheifujita commented
> @syuheifujita
> 現状だとユーザーがどのナビゲーションボタンを押しているかが分かりにくいから、非選択ボタンはグレーに選択ボタンはホワイトにするような仕様にした方が良い。
> selectorで検索してみると色々情報出てくるよ！
> 
> あとアイコンに関して、これは好みも入ってくるとは思うんやけど、自分は検索一覧画面はHOMEアイコンより虫めがねのアイコンの方がいいかなと思った。でもこれは好みの問題かと。

2020-09-06 17:02 UTC, syuheifujita commented
> @syuheifujita
> 現状だとユーザーがどのナビゲーションボタンを押しているかが分かりにくいから、非選択ボタンはグレーに選択ボタンはホワイトにするような仕様にした方が良い。
> selectorで検索してみると色々情報出てくるよ！
> 
> あとアイコンに関して、これは好みも入ってくるとは思うんやけど、自分は検索一覧画面はHOMEアイコンより虫めがねのアイコンの方がいいかなと思った。でもこれは好みの問題かと。

ここ１つ修正しました
・iconを虫メガネに変更しました
→UX目線で，どちらがベストか自分でも断定できないところもあるので

2020-09-06 17:34 UTC, taowata requested changes

2020-09-06 17:34 UTC, taowata commented on app/src/main/res/drawable/selector.xml
> +        android:drawable="@color/colorBlack" />
android:drawable → android:colorやね

2020-09-06 17:42 UTC, syuheifujita commented on app/src/main/res/drawable/selector.xml
> +        android:drawable="@color/colorBlack" />
レビューありがとう！
そこか..！color指定のミス，
<img src="https://user-images.githubusercontent.com/38001967/92331723-b5e94f80-f0b3-11ea-8039-2448a2c686b0.png" height="500">

2020-09-06 17:43 UTC, syuheifujita commented
修正
<img src="https://user-images.githubusercontent.com/38001967/92331723-b5e94f80-f0b3-11ea-8039-2448a2c686b0.png" height="500">

2020-09-07 01:12 UTC, taowata approved these changes
![LGTM](https://cdn.lgtmoon.dev/images/9309)

2020-09-07 01:13 UTC, merged

2020-09-08 14:34 UTC, syuheifujita commented
THX!